name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.ENV_PORT }}" >> .env
          echo "DB_CONNECT=${{ secrets.ENV_DB_CONNECT }}" >> .env
          echo "JWT_SECRET=${{ secrets.ENV_JWT_SECRET }}" >> .env
          echo "NODE_ENV=${{ secrets.ENV_NODE_ENV }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --if-present

      - name: Restart PM2
        run: pm2 restart index.js
